version: "3"
services:
  markovich-irc:
    build: .
    volumes:
      - /home/user/git/markovich/config-irc.json:/opt/config.json
      - /home/user/git/markovich/db:/opt/db
    restart: unless-stopped

  markovich-discord:
    build: .
    volumes:
      - /home/user/git/markovich/config-discord.json:/opt/config.json
      - /home/user/git/markovich/db:/opt/db
    restart: unless-stopped
