version: '3'
services:
  markovich:
    build: .
    volumes:
      - '/home/user/git/markovich/config.json:/opt/config.json'
      - '/home/user/git/markovich/db:/opt/db'
    ports:
      - '6697:6697'
      - '6667:6667'
    restart: unless-stopped
networks:
  znc-network:
    external: true
